In [3]:
# Step 1:Importing Libraries & Creating the dataSet
import pandas as pd
import numpy as np

data = {
    "Student_ID": list(range(101, 121)),
    "Name": [
        "Rahul", "Priya", "Amit", "Sneha", "Rohan",
        "Anjali", "Vikas", "Neha", "Arjun", "Pooja",
        "Karan", "Riya", "Sumit", "Kavya", "Manish",
        "Divya", "Raj", "Simran", "Akash", "Nisha"
    ],
    "Department": [
        "CS", "IT", "CS", "IT", "CS",
        "IT", "CS", "IT", "CS", "IT",
        "CS", "IT", "CS", "IT", "CS",
        "IT", "CS", "IT", "CS", "IT"
    ],
    "Python": [
        85, 76, 92, 45, 67, 88, 32, 79, 95, 56,
        72, 90, 41, 83, 61, 74, 87, 68, 93, 80
    ],
    "Mathematics": [
        78, 82, 95, 52, 71, 84, 40, 75, 91, 60,
        68, 89, 48, 86, 64, 79, 90, 73, 96, 85
    ],
    "English": [
        80, 74, 91, 61, 69, 90, 55, 81, 94, 58,
        75, 92, 44, 79, 66, 82, 86, 77, 89, 88
    ],
    "Attendance": [
        90, 85, 95, 72, 80, 93, 65, 88, 98, 76,
        82, 96, 70, 91, 84, 87, 92, 81, 97, 94
    ]
}

pd.DataFrame(data).to_csv("students.csv", index=False)

print("Dataset created successfully.")

Dataset created successfully.

In [4]:
# Reading & check the CsV file :
df = pd.read_csv("students.csv")

print("Total records:", len(df))
print("Columns:", df.columns.tolist())

print("\nDataset information:")
# Checking the info:
df.info()

print("\nFirst five records:")
# Checking the head:
display(df.head())

Total records: 20
Columns: ['Student_ID', 'Name', 'Department', 'Python', 'Mathematics', 'English', 'Attendance']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student_ID   20 non-null     int64
 1   Name         20 non-null     object
 2   Department   20 non-null     object
 3   Python       20 non-null     int64
 4   Mathematics  20 non-null     int64
 5   English      20 non-null     int64
 6   Attendance   20 non-null     int64
dtypes: int64(5), object(2)
memory usage: 1.2+ KB

First five records:

   Student_ID   Name Department  Python  Mathematics  English  Attendance
0         101  Rahul         CS      85           78       80          90
1         102  Priya         IT      76           82       74          85
2         103   Amit         CS      92           95       91          95
3         104  Sneha         IT      45           52       61          72
4         105  Rohan         CS      67           71       69          80

In [5]:
# Step 3 : Calculating total & average marks
subjects = ["Python", "Mathematics", "English"]

df["Total"] = df[subjects].sum(axis=1)
df["Average"] = np.round(
    df[subjects].mean(axis=1), 2
)

display(df[["Name", "Total", "Average"]])

      Name  Total  Average
0    Rahul    243    81.00
1    Priya    232    77.33
2     Amit    278    92.67
3    Sneha    158    52.67
4    Rohan    207    69.00
5   Anjali    262    87.33
6    Vikas    127    42.33
7     Neha    235    78.33
8    Arjun    280    93.33
9    Pooja    174    58.00
10   Karan    215    71.67
11    Riya    271    90.33
12   Sumit    133    44.33
13   Kavya    248    82.67
14  Manish    191    63.67
15   Divya    235    78.33
16     Raj    263    87.67
17  Simran    218    72.67
18   Akash    278    92.67
19   Nisha    253    84.33

In [6]:
# Step 4 : Creating a grade-function
def assign_grade(average):
    if average >= 90:
        return "A+"
    elif average >= 80:
        return "A"
    elif average >= 70:
        return "B"
    elif average >= 60:
        return "C"
    elif average >= 40:
        return "D"
    else:
        return "F"

df["Grade"] = df["Average"].apply(assign_grade)

display(df[["Name", "Average", "Grade"]])

      Name  Average Grade
0    Rahul    81.00     A
1    Priya    77.33     B
2     Amit    92.67    A+
3    Sneha    52.67     D
4    Rohan    69.00     C
5   Anjali    87.33     A
6    Vikas    42.33     D
7     Neha    78.33     B
8    Arjun    93.33    A+
9    Pooja    58.00     D
10   Karan    71.67     B
11    Riya    90.33    A+
12   Sumit    44.33     D
13   Kavya    82.67     A
14  Manish    63.67     C
15   Divya    78.33     B
16     Raj    87.67     A
17  Simran    72.67     B
18   Akash    92.67    A+
19   Nisha    84.33     A

In [7]:
# Step 5: Check Pass or Fail
def check_result(row):
    for subject in subjects:
        if row[subject] < 35:
            return "Fail"
    return "Pass"

df["Result"] = df.apply(check_result, axis=1)

display(df[["Name", "Python", "Mathematics",
            "English", "Result"]])

      Name  Python  Mathematics  English Result
0    Rahul      85           78       80   Pass
1    Priya      76           82       74   Pass
2     Amit      92           95       91   Pass
3    Sneha      45           52       61   Pass
4    Rohan      67           71       69   Pass
5   Anjali      88           84       90   Pass
6    Vikas      32           40       55   Fail
7     Neha      79           75       81   Pass
8    Arjun      95           91       94   Pass
9    Pooja      56           60       58   Pass
10   Karan      72           68       75   Pass
11    Riya      90           89       92   Pass
12   Sumit      41           48       44   Pass
13   Kavya      83           86       79   Pass
14  Manish      61           64       66   Pass
15   Divya      74           79       82   Pass
16     Raj      87           90       86   Pass
17  Simran      68           73       77   Pass
18   Akash      93           96       89   Pass
19   Nisha      80           85       88   Pass

In [9]:
# Step 6 : Analyzing Overall Class Performance
print("CLASS PERFORMANCE REPORT")
print("Total students:", len(df))
print("Class average:", round(np.mean(df["Average"]), 2))
print("Highest average:", df["Average"].max())
print("Lowest average:", df["Average"].min())
print("Students passed:", (df["Result"] == "Pass").sum())
print("Students failed:", (df["Result"] == "Fail").sum())

CLASS PERFORMANCE REPORT
Total students: 20
Class average: 75.02
Highest average: 93.33
Lowest average: 42.33
Students passed: 19
Students failed: 1

In [10]:
# Step 7 : Performance Subject-wise Analysis (Using a Loop)
print("SUBJECT-WISE PERFORMANCE")
for subject in subjects:
    print(
        subject,
        "average:",
        round(np.mean(df[subject]), 2)
    )

subject_averages = df[subjects].mean()
best_subject = subject_averages.idxmax()

print("\nBest-performing subject:", best_subject)

SUBJECT-WISE PERFORMANCE
Python average: 73.2
Mathematics average: 75.3
English average: 76.55

Best-performing subject: English

In [11]:
# Step 8 : Finding the Top performing Students
highest_average = df["Average"].max()

top_students = df[
    df["Average"] == highest_average
]

print("TOP-PERFORMING STUDENTS")
display(top_students[["Name", "Department", "Average", "Grade"]])

TOP-PERFORMING STUDENTS

    Name Department  Average Grade
8  Arjun         CS    93.33    A+

In [13]:
# Step 9 : Analyzing the attendance's
print("Average attendance:",
      round(df["Attendance"].mean(), 2), "%")

print("\nStudents with attendance below 75%:")

display(
    df.loc[
        df["Attendance"] < 75,
        ["Name", "Attendance"]
    ]
)

Average attendance: 85.8 %

Students with attendance below 75%:

     Name  Attendance
3   Sneha          72
6   Vikas          65
12  Sumit          70

In [15]:
# Step 10: Display the complete final report of student's
print("STUDENT PERFORMANCE ANALYTICS SYSTEM")
display(
    df[[
        "Student_ID", "Name", "Department",
        "Python", "Mathematics", "English",
        "Total", "Average", "Grade",
        "Result", "Attendance"
    ]]
)

STUDENT PERFORMANCE ANALYTICS SYSTEM

,Student_ID,Name,Department,Python,Mathematics,English,Total,Average,Grade,Result,Attendance
0,101,Rahul,CS,85,78,80,243,81.00,A,Pass,90
1,102,Priya,IT,76,82,74,232,77.33,B,Pass,85
2,103,Amit,CS,92,95,91,278,92.67,A+,Pass,95
3,104,Sneha,IT,45,52,61,158,52.67,D,Pass,72
4,105,Rohan,CS,67,71,69,207,69.00,C,Pass,80
5,106,Anjali,IT,88,84,90,262,87.33,A,Pass,93
6,107,Vikas,CS,32,40,55,127,42.33,D,Fail,65
7,108,Neha,IT,79,75,81,235,78.33,B,Pass,88
8,109,Arjun,CS,95,91,94,280,93.33,A+,Pass,98
9,110,Pooja,IT,56,60,58,174,58.00,D,Pass,76
10,111,Karan,CS,72,68,75,215,71.67,B,Pass,82
11,112,Riya,IT,90,89,92,271,90.33,A+,Pass,96
12,113,Sumit,CS,41,48,44,133,44.33,D,Pass,70
13,114,Kavya,IT,83,86,79,248,82.67,A,Pass,91
14,115,Manish,CS,61,64,66,191,63.67,C,Pass,84
15,116,Divya,IT,74,79,82,235,78.33,B,Pass,87
16,117,Raj,CS,87,90,86,263,87.67,A,Pass,92
17,118,Simran,IT,68,73,77,218,72.67,B,Pass,81
18,119,Akash,CS,93,96,89,278,92.67,A+,Pass,97
19,120,Nisha,IT,80,85,88,253,84.33,A,Pass,94

In [17]:
# Step 11 : Save the final analysis
df.to_csv("analysis_results.csv", index=False)

print("Final analysis saved to analysis_results.csv")

Final analysis saved to analysis_results.csv

In [18]:
# Step 12 : Download the files
from google.colab import files

files.download("students.csv")
files.download("analysis_results.csv")